name: Build DLL

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4   # 最新版 checkout
        with:
          lfs: true

      - name: Checkout LFS objects
        uses: actions/checkout@v4
        with:
          lfs: true
          
      - name: Verify and handle LFS files
        run: |
          echo "Checking il2cpp-types.h file size..."
          $fileSize = (Get-Item appdata\il2cpp-types.h).Length
          echo "File size: $fileSize bytes"
          if ($fileSize -lt 1000000) {
            echo "WARNING: il2cpp-types.h appears to be an LFS pointer file!"
            echo "Attempting to resolve LFS issue..."
            git lfs install
            git lfs fetch --all
            git lfs checkout
            $newFileSize = (Get-Item appdata\il2cpp-types.h).Length
            echo "New file size: $newFileSize bytes"
            if ($newFileSize -lt 1000000) {
              echo "ERROR: Failed to resolve LFS file issue!"
              Get-Content appdata\il2cpp-types.h -Head 5
              exit 1
            }
          }
          echo "LFS file verification passed."

      - name: Add MSBuild to PATH
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Build solution
        run: msbuild il2cpp-dll.sln /p:Configuration=Release /p:Platform=x64

      - name: Upload version.dll
        uses: actions/upload-artifact@v4
        with:
          name: version-dll
          path: ./x64/Release/version.dll
